Repository Quansight-Labs/bokeh-a11y-audit, pull requests merged in 2025-02, with the labels that each got.

#22 Create summary page
  source/annotations/interactions-forgivable.md
  source/annotations/non-applicable/no-table.md
  source/annotations/test-pass/color-meaning.md
  source/index.md
  source/plot-tools/assets/plot-tools_interactions-forgivable.mp4
  source/plot-tools/contrast-texture-adjustments.md
  source/plot-tools/controls-inappropriate.md
  source/plot-tools/interactions-forgivable.md
  source/plot-tools/location-history.md
  source/plot-tools/non-applicable/text-adjustments.md
  source/plot-tools/semantically-invalid.md
  source/plot-tools/style-change-respected.md
  source/plot-tools/test-pass/tedious.md
  source/plot-tools/visually-apparent-features.md
  source/plot-tools/zoom-reflow.md
  source/plotting-interface/assets/plotting-interface_no-table_1.png
  source/plotting-interface/assets/plotting-interface_no-table_2.png
  source/plotting-interface/controls-inappropriate.md
  source/plotting-interface/no-table.md
  source/plotting-interface/non-applicable/interactions-forgivable.md
  source/plotting-interface/test-pass/static-table.md
  source/summary.md
Labels: area: documentation 📖, area: audit 🔍

#29 add more info to building materials suggestion section
  source/index.md
Labels: area: audit 🔍

#32 BUG - Set RTD to single version
  .github/workflows/rtd-preview.yml
Labels: type: bug 🐛

#31 ENH - Add sphinx og meta
  environment-docs.yaml
  source/annotations/index.md
  source/conf.py
  source/images/bokeh-icon.png
  source/index.md
  source/plot-tools/index.md
  source/plotting-interface/index.md
Labels: area: documentation 📖, type: enhancement 💅🏼

#34 MAINT - Updates post release
  CITATION.cff
  README.md
  contributing.md
Labels: type: maintenance 🏗️, needs: review 👀
